
# Aggregating

In each of the examples, the expression aggregates over all the rows, and returns a single row.
That's what makes these expressions **aggregate expressions**. They can combine values from multiple rows, aggregating them together. These are different from the expressions earlier like `round`, `strsub` , which operate independently on the values in each row. Those are called non-aggregate
expressions or **scalar expressions**. They return one value per row. One need to be careful about mixing aggregate and scalar operations. You can use aggregate and scalar operations together in
an expression as in the following examples.    

```{sql connection=con}
SELECT round(AVG(salary), 1) AS avg_salary FROM employees 
```

```{sql connection=con}
SELECT SUM(salary * 0.5) AS avg_half_salary FROM employees 
```

Unfortunately, there are also invalid mix of aggregation expression and scalar expressions.

```{sql connection=con, eval = FALSE}
SELECT salary - AVG(salary) FROM employees
```

This query will throw an error message like "employees.salary must appear in the GROUP BY clause or be used in an aggregate function". For R users, this may be a bit confusing, since similar dplyr expresisons work just fine:  

```{r}
library(readr)
library(magrittr)
employees <- read_csv("data/employees.csv")

employees %>%
  mutate(difference = salary - mean(salary))
```

Anyway, the solution in SQL is to use **subqueries**:  

```{sql connection=con}
SELECT salary - 
  (SELECT AVG(salary) FROM employees)
  AS difference
FROM employees
```


Also, you cannot use scalar and aggregate expressions. For example, this query has two items in the `SELECT` list. 

```{sql connection=con, eval = FALSE}
SELECT first_name, sum(salary) FROM employees
```

The first is just the column reference first name, that evaluates as a scalar expression. It returns a value for each row in the `employees` table. The second is the aggregate expression, sum salary. That returns just one row that aggregates all the salary values in the `employees` table.
We cannot use both of these types of expressions together in one select list.   

```{sql connection=con}
SELECT red, green, blue, greatest(red, green, blue) FROM crayons
```





## The `GROUP BY` clause. 

No surprise, the `GROUP BY` clasue works hand in hand with aggregate expressions, as `group_by()` does with `summarize()` in dplyr.  

```{sql connection=con}
SELECT min_age, COUNT(*)
FROM games
WHERE list_price > 10
GROUP BY min_age;
```

Grouping expressions using column aliases, availabe in PostgreSQL, Impala, Mysql. 

```{sql connection=con}
SELECT list_price < 10 AS low_price, count(*) 
FROM games
GROUP BY low_price
```

```{sql connection=con}
SELECT list_price < 10, COUNT(*) FROM games GROUP BY list_price < 10;
```

```{sql connection=con}
SELECT list_price > 20 AS over_20, max_players, COUNT(*)
FROM games
GROUP BY over_20, max_players;
```





 

```{sql connection=con}
SELECT shop, SUM((price IS  NULL)::int), count(*) 
FROM inventory
GROUP BY shop
```


## NULL values in aggregation  

The `COUNT` function was designed to be consistent with these other aggregate functions
except in the case where you use `COUNT(*)`. So the general rule is that aggregate functions ignore `NULL` values, and the one exception to that rule is when you use `COUNT(*)`.   


With some SQL engines, you can specify more than one column reference or expression after the `DISTINCT` keyword in the `COUNT` function. This returns the number of unique combinations of the specified columns that exist in the data. This works in Hive, Impala, and MySQL, but **not** in PostgreSQL. 


```{sql connection=con, eval = FALSE}
-- this won't work in PostgreSQL
SELECT COUNT(DISTINCT red, green, blue) FROM crayons
```

Also, with some SQL engines, you can use more than one `COUNT(DISTINCT)` in a `SELECT` list,
like in this example which uses the crayons table.

```{sql connection=con}
-- PostgreSQL allow for multiple COUNT(DISTINCT) in one select list
SELECT 
  pack,
  COUNT(DISTINCT red) AS red_count,
  COUNT(DISTINCT green) AS green_count,
  COUNT(DISTINCT blue) AS blue_count
FROM crayons
GROUP BY pack
```

Here, the COUNT function is used three separate times in the `SELECT` list and the `DISTINCT` keyword is included in all three. So the result set has three columns giving the number of unique values in the red column, the number of unique values in the green column, and the number of unique values in the blue column. But with some other SQL engines including Impala, you are limited to only one` COUNT(DISTINCT)` per `SELECT` list. 

## The `HAVING` clause  

The `WHERE` clause is used before `GROUP BY` , because it makes more sense. The filter specified in the WHERE clause is used before grouping. After grouping, you can have a `HAVING` clause, which is similar to `WHERE` , except you can filter by aggregate values as well.


Often you'll want to include the aggregate expression that you use in the `HAVING` clause in the SELECT list as well. So you can see the values in the column you filtered by. In this example, the query filters by sum of price times quantity. It's good to see those sum of price times quantity values
for the rows that are included in the result set. So some of price times quantity is also used in the `SELECT` list.


```{sql connection=con}
SELECT shop, sum(qty * price)
FROM inventory
GROUP BY shop
HAVING sum(qty * price) > 300
```

But it's inconvenient to have to repeat the same expression in these two different places. So some SQL engines provide a shortcut that you can use to avoid this repetition. With some SQL engines, you can specify the aggregate expression in the `SELECT` list, give it an alias,
and then use that alias in the `HAVING` clause. That way you do not need to repeat the aggregate expression twice. This shortcut works with Impala, Hive, and MySQL but not with PostgreSQL and not with some other SQL engines. If you're using a different SQL engine, trying to see if it works.   

```{sql connection=con, eval = FALSE}
-- this does not work in PostgreSQL 
SELECT shop, sum(qty * price) AS total
FROM inventory
GROUP BY shop
HAVING total > 300
```

```{sql connection=con}
SELECT * FROM games ORDER BY min_age
```

