
# Complex Data Types 

The notion of data types underpin endless possibilities for type-specific operations. For example, we could extract the year component from a date, yet the same operation does not make any sense when applied to a string. On the other hand, regular expressions are designed for string matching problems and cannot be adapted to date. 

## Converting Data Types 

There is no guarantee that SQL will always correctly recognize the right data type for columns. `r Sys.Date()` means a date, but can be imported as a string. Since type-specific operations are only defined for certain data types. It's natural to think about converting some columnsn to the "right" data type. To change the data type of a column, we simply need to use the `column::datatype` format,
where column is the column name, and data type is the data type you want to change the column into.

`::`

`CAST`


```{sql connection=con}
SELECT shop, SUM((price IS  NULL)::int), COUNT(*) 
FROM inventory
GROUP BY shop
```



## Date and Time 

To see your current date settings, you can use the following command:

```{sql connection=con}
SHOW DateStyle
```



```{sql connection=con, eval = FALSE}
SET DateStyle='ISO, MDY';
```

In addition to displaying dates that are input as strings, we can display the current date
very simply using the `current_date` keywords in Postgres. 

Additionally, the SQL standard offers a TIMESTAMP data type. A
timestamp represents a date and a time, down to a microsecond. This can be displayed via the `current_timestamp` keyword or the `NOW()` function. 
```{sql connection=con}
SELECT current_date, current_timestamp, NOW()
```

Often, we will want to decompose our dates into their component parts. For example,
we may be interested in only the year and month, but not the day, for the monthly
analysis of our data. To do this, we can use the syntax `EXTRACT(component FROM date)`.

```{sql connection=con}
SELECT current_date,
  EXTRACT(year FROM current_date) AS year,
  EXTRACT(month FROM current_date) AS month,
  EXTRACT(day FROM current_date) AS day
```

Similarly, we can abbreviate these components as `y, `mon`, and `d`,  

```{sql connection=con}
SELECT current_date,
  EXTRACT(y FROM current_date) AS year,
  EXTRACT(mon FROM current_date) AS month,
  EXTRACT(d FROM current_date) AS day
```

We can also extract components like day of the week, week of the year, or quarter. Note that `dow` and `isodow` use different standard to extract day-of-week component. `dow` starts at 0 (Sunday) and goes up to Saturday, while `isodow` which starts at
1 (Monday) and goes up to 7 (Sunday)

```{sql connection=con}
SELECT current_date,
  EXTRACT(isodow FROM current_date) AS day_of_week,
  EXTRACT(week FROM current_date) AS week_of_year,
  EXTRACT(quarter FROM current_date) AS quarter
```

## Array  


https://www.postgresql.org/docs/current/functions-array.html#ARRAY-FUNCTIONS-TABLE

```{sql, connection=con}
SELECT 
  array[1, 2, 3, 4],
  array_length(ARRAY[1, 2, 3, 4], 1)
```

```{sql connection=con}
SELECT unnest(ARRAY[1, 2, 3]) AS unnested_array
```
```{sql connection=con}
SELECT 
  string_to_array('Hello my world', ' ')
```



## JSON       

```{sql connection=con}
SELECT
  '{
  "a": 1,
  "b": [
  {"d": 4},
  {"d": 6},
  {"d": 4}
  ],
  "c": 3
  }'::JSON -> 'b' AS data;
```


```{sql connection=con}
SELECT
  '{
  "a": 1,
  "b": [
  {"d": 4},
  {"d": 6},
  {"d": 4}
  ],
  "c": 3
  }'::JSON #> ARRAY['b', '1', 'd'] AS data;
```


## Text 

